name: Android Universal Image Loader
repository:
  type: git
  url: https://github.com/nostra13/Android-Universal-Image-Loader.git
url: https://play.google.com/store/apps/details?id=com.nostra13.universalimageloader.sample
